trigger:
- master

pool:
  name: 'private_pool'

steps:
- script: echo "Pipeline is working with self-hosted agent and fetching latest code from master branch"
  displayName: 'Verify Pipeline'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python --version
    pip install -r requirements.txt
  displayName: 'Install Python and Dependencies'