trigger:
- master

pool:
  name: 'private_pool'

variables:
  SUDO_PASSWORD: Baba12224454

steps:
- task: UseNode@1
  inputs:
    version: '14.x'
  displayName: 'Use Node.js'

- checkout: self

# Clean up old files and directories
- script: |
    echo "${SUDO_PASSWORD}" | sudo -S rm -rf $(Build.SourcesDirectory)/* 
    echo "${SUDO_PASSWORD}" | sudo -S rm -rf $(Build.ArtifactStagingDirectory)/*
  displayName: 'Clean up old files'

# Use a Docker container to run the tests
- task: Docker@2
  inputs:
    containerRegistry: ''
    repository: 'mcr.microsoft.com/playwright:v1.17.2-focal'
    command: 'run'
    arguments: '--rm -u 0:0 -v $(Build.SourcesDirectory):/app -v $(Build.ArtifactStagingDirectory):/artifacts mcr.microsoft.com/playwright:v1.17.2-focal bash -c "
      cd /app && 
      npm install && 
      npx playwright install && 
      python3 -m venv venv && 
      source venv/bin/activate && 
      pip install --upgrade pip && 
      pip install -r requirements.txt && 
      pip install pytest allure-pytest junit-xml &&
      pytest tests/test_table.py --alluredir=/artifacts/allure-results --junitxml=/artifacts/junit-results.xml &&
      allure generate /artifacts/allure-results -o /artifacts/allure-report"'
  displayName: 'Run Tests in Playwright Container'

# Publish Allure Report
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/allure-report'
    ArtifactName: 'AllureReport'
  displayName: 'Publish Allure Report'

# Publish JUnit Report
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/junit-results.xml'
    ArtifactName: 'JUnitReport'
  displayName: 'Publish JUnit Report'