name: Run Pytest with Playwright and Allure Reporting in Docker and Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.17.2-focal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pytest allure-pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Playwright Install
        run: playwright install --with-deps

      - name: Run tests with pytest and generate Allure results
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/test_table.py --alluredir=allure-results
          ls -al allure-results

      - name: Generate Allure HTML Report
        run: |
          allure generate allure-results --clean -o allure-report
          ls -al allure-report

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=allure-report --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}