# .github/workflows/ci.yml

name: Run Pytest

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip  # Upgrade pip
          pip install pytest junit-xml pytest-html  # Install pytest and necessary plugins
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install additional dependencies from requirements.txt if it exists

      - name: Run tests with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}  # Add the repository root to PYTHONPATH
        run: |
          source venv/bin/activate  # Ensure the virtual environment is activated
          mkdir -p artifacts  # Create the artifacts directory
          pytest tests/test_table.py --junitxml=artifacts/junit-results.xml --html=artifacts/test_report.html --self-contained-html  # Run pytest

      - name: Upload JUnit Test Report
        uses: actions/upload-artifact@v3
        with:
          name: JUnitReport
          path: artifacts/junit-results.xml

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v3
        with:
          name: HTMLReport
          path: artifacts/test_report.html